# ansible-playbook ansible-playbook.yaml -i localhost -K
---
- name: "Update all packages to their latest version"
  hosts: localhost
  become: true
  connection: local
  vars:
    ansible_user: vipavani
  pre_tasks:
    - name: "Update all packages to their latest version"
      apt:
        name: "*"
        state: latest
    - name: "Remove dependencies that are no longer required"
      apt:
        autoremove: yes
  tasks:
    # - include: "install/apt-playbook.yaml"
    - include: "install/flatpak-playbook.yaml"
    # - include: "install/snap-playbook.yaml"
    # - include: "install/manual-playbook.yaml"

  post_tasks:
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

