# ansible-playbook ansible-playbook.yaml -i localhost -K
---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"

    - debug: "var=output.stdout_lines"

    - include: "install/apt-playbook.yaml"
    - include: "install/flatpak-playbook.yaml"
    - include: "install/snap-playbook.yaml"

