- name: flatpak present
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install list of packages
  community.general.flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.anydesk.Anydesk
      - com.belmoussaoui.Authenticator
      - com.bitwarden.desktop
      - com.brave.Browser
      - com.calibre_ebook.calibre
      - com.getpostman.Postman
      - com.github.tchx84.Flatseal
      - com.google.Chrome
      - com.mattjakeman.ExtensionManager
      - com.mongodb.Compass
      - com.obsproject.Studio
      - com.redis.RedisInsight
      - com.slack.Slack
      - com.visualstudio.code
      - nz.mega.MEGAsync
      - org.freedesktop.Piper
      - org.libreoffice.LibreOffice
      - org.mozilla.Thunderbird
      - org.remmina.Remmina
      - org.videolan.VLC
