- name: flatpak present
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install the Spotify flatpak application
  community.general.flatpak:
    name: com.spotify.Client
    state: present
    method: user