- name: flatpak present
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install list of packages
  community.general.flatpak:
    name:
      - com.anydesk.Anydesk
      - com.belmoussaoui.Authenticator
      - com.bitwarden.desktop
      - com.calibre_ebook.calibre
      - com.getpostman.Postman
      - com.github.tchx84
      - com.google.Chrome
      - com.mongodb.Compass
      - com.redis.RedisInsight
      - com.slack.Slack
      - com.spotify.Client
      - nz.mega.MEGAsync
      - org.cryptomator.Cryptomator
      - org.gnome.Extensions
      - org.gnome.Firmware
      - org.libreoffice.LibreOffice
      - org.mozilla.Thunderbird
      - org.mozilla.firefox
      - org.remmina.Remmina
